title: Elzian Agro company
author: Chamal dissanayake
email: chamalpriyanath457@gmail.com
description: > # this means to ignore newlines until "baseurl:"
This information will add to the testing.

# social links
twitter_username: chamal dissanayake
github_username:  chamal-dissanayake
linkedin_username: chamal dissanayake

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
